{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/genesiszaim-png/chatbot/blob/main/complex_game.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "\n",
        "# =========================================================\n",
        "# SCIENCE ADVENTURE: THE LAST SCIENTIST\n",
        "# Year 6 Science Game\n",
        "# =========================================================\n",
        "\n",
        "st.set_page_config(\n",
        "    page_title=\"Science Adventure\",\n",
        "    page_icon=\"🔬\",\n",
        "    layout=\"centered\"\n",
        ")\n",
        "\n",
        "# =========================================================\n",
        "# GAME DATA\n",
        "# =========================================================\n",
        "\n",
        "levels = {\n",
        "\n",
        "    1: {\n",
        "        \"title\": \"🧬 LEVEL 1 — THE HUMAN MACHINE\",\n",
        "        \"theme\": \"Human Body & Life Processes\",\n",
        "        \"questions\": [\n",
        "\n",
        "            {\n",
        "                \"type\": \"normal\",\n",
        "                \"question\": \"Which organ pumps blood around the human body?\",\n",
        "                \"options\": [\n",
        "                    \"Lungs\",\n",
        "                    \"Heart\",\n",
        "                    \"Kidneys\",\n",
        "                    \"Stomach\"\n",
        "                ],\n",
        "                \"answer\": \"Heart\",\n",
        "                \"hint\": \"It beats continuously throughout your life.\",\n",
        "                \"explanation\": \"The heart pumps blood around the body.\"\n",
        "            },\n",
        "\n",
        "            {\n",
        "                \"type\": \"normal\",\n",
        "                \"question\": \"Which organ is mainly responsible for breathing?\",\n",
        "                \"options\": [\n",
        "                    \"Brain\",\n",
        "                    \"Heart\",\n",
        "                    \"Lungs\",\n",
        "                    \"Liver\"\n",
        "                ],\n",
        "                \"answer\": \"Lungs\",\n",
        "                \"hint\": \"Air enters and leaves these organs.\",\n",
        "                \"explanation\": \"The lungs take in oxygen and remove carbon dioxide.\"\n",
        "            },\n",
        "\n",
        "            {\n",
        "                \"type\": \"normal\",\n",
        "                \"question\": \"What is the main function of the skeleton?\",\n",
        "                \"options\": [\n",
        "                    \"To digest food\",\n",
        "                    \"To pump blood\",\n",
        "                    \"To support and protect the body\",\n",
        "                    \"To produce sunlight\"\n",
        "                ],\n",
        "                \"answer\": \"To support and protect the body\",\n",
        "                \"hint\": \"Think about your skull and rib cage.\",\n",
        "                \"explanation\": \"The skeleton supports the body and protects important organs.\"\n",
        "            },\n",
        "\n",
        "            {\n",
        "                \"type\": \"normal\",\n",
        "                \"question\": \"Which system helps break food into nutrients?\",\n",
        "                \"options\": [\n",
        "                    \"Digestive system\",\n",
        "                    \"Respiratory system\",\n",
        "                    \"Nervous system\",\n",
        "                    \"Skeletal system\"\n",
        "                ],\n",
        "                \"answer\": \"Digestive system\",\n",
        "                \"hint\": \"Food travels through this system.\",\n",
        "                \"explanation\": \"The digestive system breaks food down so the body can absorb nutrients.\"\n",
        "            },\n",
        "\n",
        "            {\n",
        "                \"type\": \"boss\",\n",
        "                \"question\": \"🧠 BOSS CHALLENGE: A student runs quickly for 5 minutes. Why does the student's breathing rate increase?\",\n",
        "                \"options\": [\n",
        "                    \"The body needs more oxygen\",\n",
        "                    \"The bones become heavier\",\n",
        "                    \"The stomach stops working\",\n",
        "                    \"The brain stops receiving oxygen\"\n",
        "                ],\n",
        "                \"answer\": \"The body needs more oxygen\",\n",
        "                \"hint\": \"Muscles need oxygen when they work harder.\",\n",
        "                \"explanation\": \"During exercise, muscles need more oxygen, so breathing becomes faster.\"\n",
        "            }\n",
        "        ]\n",
        "    },\n",
        "\n",
        "    2: {\n",
        "        \"title\": \"⚡ LEVEL 2 — POWER STATION\",\n",
        "        \"theme\": \"Electricity, Energy & Forces\",\n",
        "        \"questions\": [\n",
        "\n",
        "            {\n",
        "                \"type\": \"normal\",\n",
        "                \"question\": \"Which material is usually a good conductor of electricity?\",\n",
        "                \"options\": [\n",
        "                    \"Copper\",\n",
        "                    \"Rubber\",\n",
        "                    \"Plastic\",\n",
        "                    \"Wood\"\n",
        "                ],\n",
        "                \"answer\": \"Copper\",\n",
        "                \"hint\": \"It is commonly used inside electrical wires.\",\n",
        "                \"explanation\": \"Copper conducts electricity well and is commonly used in wires.\"\n",
        "            },\n",
        "\n",
        "            {\n",
        "                \"type\": \"normal\",\n",
        "                \"question\": \"What happens when a circuit is incomplete?\",\n",
        "                \"options\": [\n",
        "                    \"Electric current flows normally\",\n",
        "                    \"The bulb becomes brighter\",\n",
        "                    \"Electric current cannot flow around the circuit\",\n",
        "                    \"The battery becomes larger\"\n",
        "                ],\n",
        "                \"answer\": \"Electric current cannot flow around the circuit\",\n",
        "                \"hint\": \"A circuit needs a complete path.\",\n",
        "                \"explanation\": \"Electric current needs a complete circuit to flow.\"\n",
        "            },\n",
        "\n",
        "            {\n",
        "                \"type\": \"normal\",\n",
        "                \"question\": \"Which force pulls objects towards Earth?\",\n",
        "                \"options\": [\n",
        "                    \"Friction\",\n",
        "                    \"Gravity\",\n",
        "                    \"Magnetism\",\n",
        "                    \"Air resistance\"\n",
        "                ],\n",
        "                \"answer\": \"Gravity\",\n",
        "                \"hint\": \"It is why objects fall when dropped.\",\n",
        "                \"explanation\": \"Gravity pulls objects towards Earth.\"\n",
        "            },\n",
        "\n",
        "            {\n",
        "                \"type\": \"normal\",\n",
        "                \"question\": \"Which force slows down a sliding object?\",\n",
        "                \"options\": [\n",
        "                    \"Gravity\",\n",
        "                    \"Friction\",\n",
        "                    \"Light\",\n",
        "                    \"Sound\"\n",
        "                ],\n",
        "                \"answer\": \"Friction\",\n",
        "                \"hint\": \"It happens when two surfaces rub against each other.\",\n",
        "                \"explanation\": \"Friction opposes motion between surfaces.\"\n",
        "            },\n",
        "\n",
        "            {\n",
        "                \"type\": \"boss\",\n",
        "                \"question\": \"⚡ BOSS CHALLENGE: A bulb does not light even though the battery works. What should you check first?\",\n",
        "                \"options\": [\n",
        "                    \"Whether the circuit is complete\",\n",
        "                    \"Whether the table is heavy\",\n",
        "                    \"Whether the room is cold\",\n",
        "                    \"Whether the bulb is colourful\"\n",
        "                ],\n",
        "                \"answer\": \"Whether the circuit is complete\",\n",
        "                \"hint\": \"Electricity needs a continuous path.\",\n",
        "                \"explanation\": \"A complete circuit is necessary for electric current to flow.\"\n",
        "            }\n",
        "        ]\n",
        "    },\n",
        "\n",
        "    3: {\n",
        "        \"title\": \"🌍 LEVEL 3 — PLANET IN DANGER\",\n",
        "        \"theme\": \"Earth, Space & Environment\",\n",
        "        \"questions\": [\n",
        "\n",
        "            {\n",
        "                \"type\": \"normal\",\n",
        "                \"question\": \"What causes day and night on Earth?\",\n",
        "                \"options\": [\n",
        "                    \"Earth rotating on its axis\",\n",
        "                    \"The Moon changing shape\",\n",
        "                    \"Clouds moving\",\n",
        "                    \"The Sun switching on and off\"\n",
        "                ],\n",
        "                \"answer\": \"Earth rotating on its axis\",\n",
        "                \"hint\": \"Earth spins.\",\n",
        "                \"explanation\": \"Earth rotates on its axis, causing different parts to face the Sun.\"\n",
        "            },\n",
        "\n",
        "            {\n",
        "                \"type\": \"normal\",\n",
        "                \"question\": \"Which planet is famous for its prominent rings?\",\n",
        "                \"options\": [\n",
        "                    \"Mars\",\n",
        "                    \"Venus\",\n",
        "                    \"Saturn\",\n",
        "                    \"Mercury\"\n",
        "                ],\n",
        "                \"answer\": \"Saturn\",\n",
        "                \"hint\": \"It is one of the outer planets.\",\n",
        "                \"explanation\": \"Saturn is well known for its large ring system.\"\n",
        "            },\n",
        "\n",
        "            {\n",
        "                \"type\": \"normal\",\n",
        "                \"question\": \"Which gas is needed by humans for respiration?\",\n",
        "                \"options\": [\n",
        "                    \"Oxygen\",\n",
        "                    \"Carbon dioxide\",\n",
        "                    \"Nitrogen only\",\n",
        "                    \"Helium\"\n",
        "                ],\n",
        "                \"answer\": \"Oxygen\",\n",
        "                \"hint\": \"We breathe it in from the air.\",\n",
        "                \"explanation\": \"Humans use oxygen during respiration.\"\n",
        "            },\n",
        "\n",
        "            {\n",
        "                \"type\": \"normal\",\n",
        "                \"question\": \"Which action can help reduce waste?\",\n",
        "                \"options\": [\n",
        "                    \"Throwing everything away\",\n",
        "                    \"Using disposable items once\",\n",
        "                    \"Reusing materials\",\n",
        "                    \"Leaving rubbish outdoors\"\n",
        "                ],\n",
        "                \"answer\": \"Reusing materials\",\n",
        "                \"hint\": \"Use something again instead of throwing it away.\",\n",
        "                \"explanation\": \"Reusing materials can reduce the amount of waste produced.\"\n",
        "            },\n",
        "\n",
        "            {\n",
        "                \"type\": \"boss\",\n",
        "                \"question\": \"🌎 FINAL BOSS: A forest is removed from a large area. Which is a likely environmental consequence?\",\n",
        "                \"options\": [\n",
        "                    \"More habitats are available\",\n",
        "                    \"Some animals may lose their habitats\",\n",
        "                    \"There will be more trees\",\n",
        "                    \"The amount of forest increases\"\n",
        "                ],\n",
        "                \"answer\": \"Some animals may lose their habitats\",\n",
        "                \"hint\": \"Think about where forest animals live.\",\n",
        "                \"explanation\": \"Removing forests can destroy habitats and reduce biodiversity.\"\n",
        "            }\n",
        "        ]\n",
        "    }\n",
        "}\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SESSION STATE\n",
        "# =========================================================\n",
        "\n",
        "defaults = {\n",
        "    \"started\": False,\n",
        "    \"level\": 1,\n",
        "    \"question\": 0,\n",
        "    \"score\": 0,\n",
        "    \"lives\": 3,\n",
        "    \"energy\": 3,\n",
        "    \"streak\": 0,\n",
        "    \"best_streak\": 0,\n",
        "    \"hints_used\": 0,\n",
        "    \"correct\": 0,\n",
        "    \"wrong\": 0,\n",
        "    \"game_over\": False,\n",
        "    \"finished\": False,\n",
        "    \"hint\": False,\n",
        "    \"answered\": False\n",
        "}\n",
        "\n",
        "for key, value in defaults.items():\n",
        "    if key not in st.session_state:\n",
        "        st.session_state[key] = value\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# RESET GAME\n",
        "# =========================================================\n",
        "\n",
        "def reset_game():\n",
        "\n",
        "    for key, value in defaults.items():\n",
        "        st.session_state[key] = value\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# START SCREEN\n",
        "# =========================================================\n",
        "\n",
        "if not st.session_state.started:\n",
        "\n",
        "    st.title(\"🔬 SCIENCE ADVENTURE\")\n",
        "\n",
        "    st.subheader(\"⚠️ THE LAST SCIENTIST\")\n",
        "\n",
        "    st.write(\n",
        "        \"The Science Laboratory has lost its power. \"\n",
        "        \"Only a young scientist can restore it.\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        \"Complete three dangerous science missions, \"\n",
        "        \"defeat the Boss Challenges and save the laboratory!\"\n",
        "    )\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "    st.markdown(\"\"\"\n",
        "    ### 🎮 YOUR MISSION\n",
        "\n",
        "    🧬 **Level 1:** The Human Machine\n",
        "\n",
        "    ⚡ **Level 2:** Power Station\n",
        "\n",
        "    🌍 **Level 3:** Planet in Danger\n",
        "\n",
        "    ### ❤️ YOUR RESOURCES\n",
        "\n",
        "    ❤️ **3 Lives**\n",
        "\n",
        "    ⚡ **3 Science Energy**\n",
        "\n",
        "    ⭐ Earn **XP points**\n",
        "\n",
        "    🔥 Build a **correct-answer streak**\n",
        "\n",
        "    💡 Use Science Energy to get hints\n",
        "    \"\"\")\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "    if st.button(\n",
        "        \"🚀 BEGIN MISSION\",\n",
        "        use_container_width=True\n",
        "    ):\n",
        "\n",
        "        st.session_state.started = True\n",
        "        st.rerun()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GAME OVER\n",
        "# =========================================================\n",
        "\n",
        "elif st.session_state.game_over:\n",
        "\n",
        "    st.title(\"💥 MISSION FAILED\")\n",
        "\n",
        "    st.error(\"You have lost all your lives.\")\n",
        "\n",
        "    st.write(\n",
        "        f\"⭐ XP: **{st.session_state.score}**\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        f\"🔥 Best streak: **{st.session_state.best_streak}**\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        \"Every scientist makes mistakes. \"\n",
        "        \"Study the explanations and try again!\"\n",
        "    )\n",
        "\n",
        "    if st.button(\n",
        "        \"🔄 RESTART MISSION\",\n",
        "        use_container_width=True\n",
        "    ):\n",
        "\n",
        "        reset_game()\n",
        "        st.rerun()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# FINAL SCREEN\n",
        "# =========================================================\n",
        "\n",
        "elif st.session_state.finished:\n",
        "\n",
        "    st.title(\"🏆 MISSION COMPLETE!\")\n",
        "\n",
        "    st.balloons()\n",
        "\n",
        "    score = st.session_state.score\n",
        "\n",
        "    st.subheader(\"🌟 YOU ARE A SCIENCE HERO!\")\n",
        "\n",
        "    st.metric(\n",
        "        \"TOTAL XP\",\n",
        "        score\n",
        "    )\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "    col1, col2, col3 = st.columns(3)\n",
        "\n",
        "    with col1:\n",
        "        st.metric(\n",
        "            \"✅ Correct\",\n",
        "            st.session_state.correct\n",
        "        )\n",
        "\n",
        "    with col2:\n",
        "        st.metric(\n",
        "            \"❌ Wrong\",\n",
        "            st.session_state.wrong\n",
        "        )\n",
        "\n",
        "    with col3:\n",
        "        st.metric(\n",
        "            \"🔥 Best Streak\",\n",
        "            st.session_state.best_streak\n",
        "        )\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "    if score >= 250:\n",
        "        st.success(\n",
        "            \"🥇 MASTER SCIENTIST — Outstanding scientific thinking!\"\n",
        "        )\n",
        "\n",
        "    elif score >= 200:\n",
        "        st.success(\n",
        "            \"🥈 SENIOR SCIENTIST — Excellent work!\"\n",
        "        )\n",
        "\n",
        "    elif score >= 150:\n",
        "        st.info(\n",
        "            \"🥉 SCIENCE EXPLORER — Great job!\"\n",
        "        )\n",
        "\n",
        "    else:\n",
        "        st.warning(\n",
        "            \"🔬 SCIENCE ROOKIE — Keep exploring and learning!\"\n",
        "        )\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "    st.subheader(\"📊 Mission Report\")\n",
        "\n",
        "    accuracy = (\n",
        "        st.session_state.correct / 15\n",
        "    ) * 100\n",
        "\n",
        "    st.write(\n",
        "        f\"Accuracy: **{accuracy:.0f}%**\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        f\"Hints used: **{st.session_state.hints_used}**\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        f\"Best answer streak: **{st.session_state.best_streak}**\"\n",
        "    )\n",
        "\n",
        "    if st.button(\n",
        "        \"🔄 PLAY AGAIN\",\n",
        "        use_container_width=True\n",
        "    ):\n",
        "\n",
        "        reset_game()\n",
        "        st.rerun()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# MAIN GAME\n",
        "# =========================================================\n",
        "\n",
        "else:\n",
        "\n",
        "    level = st.session_state.level\n",
        "\n",
        "    level_data = levels[level]\n",
        "\n",
        "    question_number = st.session_state.question\n",
        "\n",
        "    question_data = level_data[\"questions\"][question_number]\n",
        "\n",
        "\n",
        "    # =====================================================\n",
        "    # HEADER\n",
        "    # =====================================================\n",
        "\n",
        "    st.title(\"🔬 SCIENCE ADVENTURE\")\n",
        "\n",
        "    st.subheader(level_data[\"title\"])\n",
        "\n",
        "    st.caption(level_data[\"theme\"])\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "\n",
        "    # =====================================================\n",
        "    # PLAYER STATUS\n",
        "    # =====================================================\n",
        "\n",
        "    col1, col2, col3, col4 = st.columns(4)\n",
        "\n",
        "    with col1:\n",
        "        st.metric(\n",
        "            \"⭐ XP\",\n",
        "            st.session_state.score\n",
        "        )\n",
        "\n",
        "    with col2:\n",
        "        st.metric(\n",
        "            \"❤️ Lives\",\n",
        "            st.session_state.lives\n",
        "        )\n",
        "\n",
        "    with col3:\n",
        "        st.metric(\n",
        "            \"⚡ Energy\",\n",
        "            st.session_state.energy\n",
        "        )\n",
        "\n",
        "    with col4:\n",
        "        st.metric(\n",
        "            \"🔥 Streak\",\n",
        "            st.session_state.streak\n",
        "        )\n",
        "\n",
        "\n",
        "    # =====================================================\n",
        "    # LEVEL PROGRESS\n",
        "    # =====================================================\n",
        "\n",
        "    st.progress(\n",
        "        (question_number + 1)\n",
        "        / len(level_data[\"questions\"])\n",
        "    )\n",
        "\n",
        "    if question_data[\"type\"] == \"boss\":\n",
        "\n",
        "        st.warning(\n",
        "            \"⚔️ BOSS CHALLENGE — Defeat the Science Boss!\"\n",
        "        )\n",
        "\n",
        "    else:\n",
        "\n",
        "        st.info(\n",
        "            f\"Mission Challenge {question_number + 1} \"\n",
        "            f\"of {len(level_data['questions'])}\"\n",
        "        )\n",
        "\n",
        "\n",
        "    # =====================================================\n",
        "    # QUESTION\n",
        "    # =====================================================\n",
        "\n",
        "    st.markdown(\n",
        "        f\"## 🧠 {question_data['question']}\"\n",
        "    )\n",
        "\n",
        "\n",
        "    # =====================================================\n",
        "    # HINT\n",
        "    # =====================================================\n",
        "\n",
        "    if st.session_state.energy > 0:\n",
        "\n",
        "        if st.button(\n",
        "            \"💡 USE SCIENCE ENERGY FOR A HINT\"\n",
        "        ):\n",
        "\n",
        "            st.session_state.energy -= 1\n",
        "\n",
        "            st.session_state.hints_used += 1\n",
        "\n",
        "            st.session_state.hint = True\n",
        "\n",
        "            st.rerun()\n",
        "\n",
        "    else:\n",
        "\n",
        "        st.caption(\n",
        "            \"⚡ You have no Science Energy left.\"\n",
        "        )\n",
        "\n",
        "\n",
        "    if st.session_state.hint:\n",
        "\n",
        "        st.warning(\n",
        "            f\"💡 HINT: {question_data['hint']}\"\n",
        "        )\n",
        "\n",
        "\n",
        "    # =====================================================\n",
        "    # ANSWER\n",
        "    # =====================================================\n",
        "\n",
        "    answer = st.radio(\n",
        "        \"Choose your answer:\",\n",
        "        question_data[\"options\"],\n",
        "        key=f\"answer_{level}_{question_number}\"\n",
        "    )\n",
        "\n",
        "\n",
        "    # =====================================================\n",
        "    # SUBMIT ANSWER\n",
        "    # =====================================================\n",
        "\n",
        "    if st.button(\n",
        "        \"🚀 SUBMIT ANSWER\",\n",
        "        use_container_width=True\n",
        "    ):\n",
        "\n",
        "        if answer == question_data[\"answer\"]:\n",
        "\n",
        "            # ---------------------------------------------\n",
        "            # CORRECT\n",
        "            # ---------------------------------------------\n",
        "\n",
        "            st.session_state.correct += 1\n",
        "\n",
        "            st.session_state.streak += 1\n",
        "\n",
        "            if (\n",
        "                st.session_state.streak\n",
        "                > st.session_state.best_streak\n",
        "            ):\n",
        "\n",
        "                st.session_state.best_streak = (\n",
        "                    st.session_state.streak\n",
        "                )\n",
        "\n",
        "\n",
        "            # Base XP\n",
        "            points = 20\n",
        "\n",
        "            # Streak bonus\n",
        "            if st.session_state.streak >= 3:\n",
        "\n",
        "                points += 10\n",
        "\n",
        "            # Boss bonus\n",
        "            if question_data[\"type\"] == \"boss\":\n",
        "\n",
        "                points += 20\n",
        "\n",
        "\n",
        "            st.session_state.score += points\n",
        "\n",
        "\n",
        "            st.success(\n",
        "                f\"🎉 CORRECT! +{points} XP\"\n",
        "            )\n",
        "\n",
        "            st.write(\n",
        "                f\"🧠 {question_data['explanation']}\"\n",
        "            )\n",
        "\n",
        "\n",
        "            # Reset hint\n",
        "            st.session_state.hint = False\n",
        "\n",
        "\n",
        "            # Move to next question\n",
        "            st.session_state.question += 1\n",
        "\n",
        "\n",
        "            # ---------------------------------------------\n",
        "            # LEVEL COMPLETED\n",
        "            # ---------------------------------------------\n",
        "\n",
        "            if (\n",
        "                st.session_state.question\n",
        "                >= len(level_data[\"questions\"])\n",
        "            ):\n",
        "\n",
        "                if level == 3:\n",
        "\n",
        "                    st.session_state.finished = True\n",
        "\n",
        "                else:\n",
        "\n",
        "                    st.session_state.level += 1\n",
        "\n",
        "                    st.session_state.question = 0\n",
        "\n",
        "                    st.session_state.energy += 1\n",
        "\n",
        "                    st.balloons()\n",
        "\n",
        "                    st.info(\n",
        "                        f\"🔓 LEVEL {level + 1} UNLOCKED!\"\n",
        "                    )\n",
        "\n",
        "            st.rerun()\n",
        "\n",
        "\n",
        "        else:\n",
        "\n",
        "            # ---------------------------------------------\n",
        "            # WRONG\n",
        "            # ---------------------------------------------\n",
        "\n",
        "            st.session_state.wrong += 1\n",
        "\n",
        "            st.session_state.lives -= 1\n",
        "\n",
        "            st.session_state.streak = 0\n",
        "\n",
        "            st.session_state.hint = False\n",
        "\n",
        "            st.error(\"❌ INCORRECT!\")\n",
        "\n",
        "            st.write(\n",
        "                f\"💡 Correct answer: \"\n",
        "                f\"**{question_data['answer']}**\"\n",
        "            )\n",
        "\n",
        "            st.write(\n",
        "                f\"🧠 Explanation: \"\n",
        "                f\"{question_data['explanation']}\"\n",
        "            )\n",
        "\n",
        "\n",
        "            # ---------------------------------------------\n",
        "            # GAME OVER\n",
        "            # ---------------------------------------------\n",
        "\n",
        "            if st.session_state.lives <= 0:\n",
        "\n",
        "                st.session_state.game_over = True\n",
        "\n",
        "            else:\n",
        "\n",
        "                st.session_state.question += 1\n",
        "\n",
        "\n",
        "                # Level progression\n",
        "                if (\n",
        "                    st.session_state.question\n",
        "                    >= len(level_data[\"questions\"])\n",
        "                ):\n",
        "\n",
        "                    if level == 3:\n",
        "\n",
        "                        st.session_state.finished = True\n",
        "\n",
        "                    else:\n",
        "\n",
        "                        st.session_state.level += 1\n",
        "\n",
        "                        st.session_state.question = 0\n",
        "\n",
        "                        st.session_state.energy += 1\n",
        "\n",
        "            st.rerun()"
      ],
      "metadata": {
        "id": "phTsvvMkYMiM"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}