{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyP9ay8rx2Ppkm9pOv2ANsH7",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/genesiszaim-png/chatbot/blob/main/game_baru.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import random\n",
        "import time\n",
        "\n",
        "# =========================================================\n",
        "# PAGE CONFIG\n",
        "# =========================================================\n",
        "\n",
        "st.set_page_config(\n",
        "    page_title=\"Math Adventure\",\n",
        "    page_icon=\"🧮\",\n",
        "    layout=\"wide\"\n",
        ")\n",
        "\n",
        "# =========================================================\n",
        "# CUSTOM CSS\n",
        "# =========================================================\n",
        "\n",
        "st.markdown(\"\"\"\n",
        "<style>\n",
        "\n",
        ".main-title {\n",
        "    text-align: center;\n",
        "    font-size: 48px;\n",
        "    font-weight: 800;\n",
        "    margin-bottom: 0;\n",
        "}\n",
        "\n",
        ".subtitle {\n",
        "    text-align: center;\n",
        "    font-size: 20px;\n",
        "    margin-bottom: 30px;\n",
        "}\n",
        "\n",
        ".dashboard-card {\n",
        "    padding: 18px;\n",
        "    border-radius: 15px;\n",
        "    border: 1px solid #ddd;\n",
        "    text-align: center;\n",
        "    margin-bottom: 15px;\n",
        "}\n",
        "\n",
        ".question-card {\n",
        "    padding: 35px;\n",
        "    border-radius: 20px;\n",
        "    border: 2px solid #ddd;\n",
        "    text-align: center;\n",
        "    margin: 20px 0;\n",
        "}\n",
        "\n",
        ".big-question {\n",
        "    font-size: 48px;\n",
        "    font-weight: bold;\n",
        "}\n",
        "\n",
        ".badge {\n",
        "    padding: 12px;\n",
        "    border-radius: 12px;\n",
        "    border: 1px solid #ddd;\n",
        "    text-align: center;\n",
        "    margin-bottom: 10px;\n",
        "}\n",
        "\n",
        "</style>\n",
        "\"\"\", unsafe_allow_html=True)\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# QUESTION GENERATOR\n",
        "# =========================================================\n",
        "\n",
        "def generate_question(category, difficulty):\n",
        "\n",
        "    if difficulty == \"Easy\":\n",
        "        max_num = 20\n",
        "\n",
        "    elif difficulty == \"Medium\":\n",
        "        max_num = 50\n",
        "\n",
        "    else:\n",
        "        max_num = 100\n",
        "\n",
        "    # -----------------------------\n",
        "    # Addition\n",
        "    # -----------------------------\n",
        "\n",
        "    if category == \"Addition\":\n",
        "\n",
        "        a = random.randint(1, max_num)\n",
        "        b = random.randint(1, max_num)\n",
        "\n",
        "        question = f\"{a} + {b}\"\n",
        "        answer = a + b\n",
        "\n",
        "    # -----------------------------\n",
        "    # Subtraction\n",
        "    # -----------------------------\n",
        "\n",
        "    elif category == \"Subtraction\":\n",
        "\n",
        "        a = random.randint(1, max_num)\n",
        "        b = random.randint(1, max_num)\n",
        "\n",
        "        if b > a:\n",
        "            a, b = b, a\n",
        "\n",
        "        question = f\"{a} − {b}\"\n",
        "        answer = a - b\n",
        "\n",
        "    # -----------------------------\n",
        "    # Multiplication\n",
        "    # -----------------------------\n",
        "\n",
        "    elif category == \"Multiplication\":\n",
        "\n",
        "        if difficulty == \"Easy\":\n",
        "            a = random.randint(1, 10)\n",
        "            b = random.randint(1, 10)\n",
        "\n",
        "        elif difficulty == \"Medium\":\n",
        "            a = random.randint(2, 15)\n",
        "            b = random.randint(2, 15)\n",
        "\n",
        "        else:\n",
        "            a = random.randint(5, 25)\n",
        "            b = random.randint(5, 25)\n",
        "\n",
        "        question = f\"{a} × {b}\"\n",
        "        answer = a * b\n",
        "\n",
        "    # -----------------------------\n",
        "    # Division\n",
        "    # -----------------------------\n",
        "\n",
        "    else:\n",
        "\n",
        "        b = random.randint(2, 12)\n",
        "        answer = random.randint(2, max_num // 2)\n",
        "\n",
        "        a = b * answer\n",
        "\n",
        "        question = f\"{a} ÷ {b}\"\n",
        "        answer = answer\n",
        "\n",
        "    return question, answer\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# CREATE OPTIONS\n",
        "# =========================================================\n",
        "\n",
        "def create_options(correct):\n",
        "\n",
        "    options = {correct}\n",
        "\n",
        "    while len(options) < 4:\n",
        "\n",
        "        difference = random.randint(-15, 15)\n",
        "\n",
        "        if difference == 0:\n",
        "            continue\n",
        "\n",
        "        option = correct + difference\n",
        "\n",
        "        if option >= 0:\n",
        "            options.add(option)\n",
        "\n",
        "    options = list(options)\n",
        "\n",
        "    random.shuffle(options)\n",
        "\n",
        "    return options\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# START GAME\n",
        "# =========================================================\n",
        "\n",
        "def start_game():\n",
        "\n",
        "    category = st.session_state.category\n",
        "    difficulty = st.session_state.difficulty\n",
        "\n",
        "    question, answer = generate_question(\n",
        "        category,\n",
        "        difficulty\n",
        "    )\n",
        "\n",
        "    st.session_state.question = question\n",
        "    st.session_state.correct_answer = answer\n",
        "\n",
        "    st.session_state.options = create_options(answer)\n",
        "\n",
        "    st.session_state.question_number = 1\n",
        "    st.session_state.score = 0\n",
        "    st.session_state.correct = 0\n",
        "    st.session_state.wrong = 0\n",
        "    st.session_state.streak = 0\n",
        "    st.session_state.best_streak = 0\n",
        "    st.session_state.lives = 3\n",
        "    st.session_state.xp = 0\n",
        "\n",
        "    st.session_state.game_started = True\n",
        "    st.session_state.game_over = False\n",
        "    st.session_state.answered = False\n",
        "\n",
        "    st.session_state.start_time = time.time()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# NEXT QUESTION\n",
        "# =========================================================\n",
        "\n",
        "def next_question():\n",
        "\n",
        "    question, answer = generate_question(\n",
        "        st.session_state.category,\n",
        "        st.session_state.difficulty\n",
        "    )\n",
        "\n",
        "    st.session_state.question = question\n",
        "    st.session_state.correct_answer = answer\n",
        "\n",
        "    st.session_state.options = create_options(answer)\n",
        "\n",
        "    st.session_state.question_number += 1\n",
        "    st.session_state.answered = False\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SESSION STATE\n",
        "# =========================================================\n",
        "\n",
        "if \"game_started\" not in st.session_state:\n",
        "\n",
        "    st.session_state.game_started = False\n",
        "\n",
        "    st.session_state.category = \"Addition\"\n",
        "\n",
        "    st.session_state.difficulty = \"Easy\"\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# TITLE\n",
        "# =========================================================\n",
        "\n",
        "st.markdown(\n",
        "    '<div class=\"main-title\">🧮 MATH ADVENTURE</div>',\n",
        "    unsafe_allow_html=True\n",
        ")\n",
        "\n",
        "st.markdown(\n",
        "    '<div class=\"subtitle\">Train your brain. Build your streak. Become a Math Master!</div>',\n",
        "    unsafe_allow_html=True\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SETUP SCREEN\n",
        "# =========================================================\n",
        "\n",
        "if not st.session_state.game_started:\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    st.subheader(\"🎮 Game Setup\")\n",
        "\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "\n",
        "        category = st.selectbox(\n",
        "            \"🧮 Choose Math Topic\",\n",
        "            [\n",
        "                \"Addition\",\n",
        "                \"Subtraction\",\n",
        "                \"Multiplication\",\n",
        "                \"Division\"\n",
        "            ]\n",
        "        )\n",
        "\n",
        "    with col2:\n",
        "\n",
        "        difficulty = st.selectbox(\n",
        "            \"🎯 Choose Difficulty\",\n",
        "            [\n",
        "                \"Easy\",\n",
        "                \"Medium\",\n",
        "                \"Hard\"\n",
        "            ]\n",
        "        )\n",
        "\n",
        "    st.write(\"\")\n",
        "\n",
        "    st.info(\n",
        "        \"💡 Answer 10 questions. \"\n",
        "        \"Correct answers increase your score and streak. \"\n",
        "        \"You have 3 lives!\"\n",
        "    )\n",
        "\n",
        "    st.write(\"\")\n",
        "\n",
        "    if st.button(\n",
        "        \"🚀 START MATH ADVENTURE\",\n",
        "        use_container_width=True\n",
        "    ):\n",
        "\n",
        "        st.session_state.category = category\n",
        "        st.session_state.difficulty = difficulty\n",
        "\n",
        "        start_game()\n",
        "\n",
        "        st.rerun()\n",
        "\n",
        "    st.stop()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GAME OVER\n",
        "# =========================================================\n",
        "\n",
        "if st.session_state.game_over:\n",
        "\n",
        "    st.balloons()\n",
        "\n",
        "    st.header(\"🏆 GAME COMPLETE!\")\n",
        "\n",
        "    score = st.session_state.score\n",
        "    correct = st.session_state.correct\n",
        "    wrong = st.session_state.wrong\n",
        "\n",
        "    accuracy = 0\n",
        "\n",
        "    if correct + wrong > 0:\n",
        "        accuracy = round(\n",
        "            correct / (correct + wrong) * 100\n",
        "        )\n",
        "\n",
        "    col1, col2, col3, col4 = st.columns(4)\n",
        "\n",
        "    col1.metric(\n",
        "        \"⭐ Score\",\n",
        "        score\n",
        "    )\n",
        "\n",
        "    col2.metric(\n",
        "        \"✅ Correct\",\n",
        "        correct\n",
        "    )\n",
        "\n",
        "    col3.metric(\n",
        "        \"❌ Wrong\",\n",
        "        wrong\n",
        "    )\n",
        "\n",
        "    col4.metric(\n",
        "        \"🎯 Accuracy\",\n",
        "        f\"{accuracy}%\"\n",
        "    )\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    if score >= 900:\n",
        "\n",
        "        st.success(\n",
        "            \"🌟 LEGENDARY MATH MASTER!\"\n",
        "        )\n",
        "\n",
        "    elif score >= 700:\n",
        "\n",
        "        st.success(\n",
        "            \"🔥 Excellent performance!\"\n",
        "        )\n",
        "\n",
        "    elif score >= 500:\n",
        "\n",
        "        st.info(\n",
        "            \"👏 Great job! Keep practising!\"\n",
        "        )\n",
        "\n",
        "    else:\n",
        "\n",
        "        st.warning(\n",
        "            \"💪 Keep practising. You are improving!\"\n",
        "        )\n",
        "\n",
        "    st.subheader(\"🏅 Achievements\")\n",
        "\n",
        "    badges = []\n",
        "\n",
        "    if correct >= 8:\n",
        "        badges.append(\"🎯 Accuracy Champion\")\n",
        "\n",
        "    if st.session_state.best_streak >= 5:\n",
        "        badges.append(\"🔥 Streak Master\")\n",
        "\n",
        "    if score >= 700:\n",
        "        badges.append(\"⭐ High Scorer\")\n",
        "\n",
        "    if len(badges) == 0:\n",
        "        badges.append(\"🌱 Keep Learning\")\n",
        "\n",
        "    badge_cols = st.columns(len(badges))\n",
        "\n",
        "    for i, badge in enumerate(badges):\n",
        "\n",
        "        badge_cols[i].markdown(\n",
        "            f\"\"\"\n",
        "            <div class=\"badge\">\n",
        "            <h3>{badge}</h3>\n",
        "            </div>\n",
        "            \"\"\",\n",
        "            unsafe_allow_html=True\n",
        "        )\n",
        "\n",
        "    st.write(\"\")\n",
        "\n",
        "    if st.button(\n",
        "        \"🔄 PLAY AGAIN\",\n",
        "        use_container_width=True\n",
        "    ):\n",
        "\n",
        "        st.session_state.game_started = False\n",
        "        st.session_state.game_over = False\n",
        "\n",
        "        st.rerun()\n",
        "\n",
        "    st.stop()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# GAME DASHBOARD\n",
        "# =========================================================\n",
        "\n",
        "st.divider()\n",
        "\n",
        "col1, col2, col3, col4, col5 = st.columns(5)\n",
        "\n",
        "with col1:\n",
        "\n",
        "    st.metric(\n",
        "        \"⭐ Score\",\n",
        "        st.session_state.score\n",
        "    )\n",
        "\n",
        "with col2:\n",
        "\n",
        "    st.metric(\n",
        "        \"🔥 Streak\",\n",
        "        st.session_state.streak\n",
        "    )\n",
        "\n",
        "with col3:\n",
        "\n",
        "    st.metric(\n",
        "        \"🏆 Best Streak\",\n",
        "        st.session_state.best_streak\n",
        "    )\n",
        "\n",
        "with col4:\n",
        "\n",
        "    st.metric(\n",
        "        \"❤️ Lives\",\n",
        "        st.session_state.lives\n",
        "    )\n",
        "\n",
        "with col5:\n",
        "\n",
        "    st.metric(\n",
        "        \"⚡ XP\",\n",
        "        st.session_state.xp\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# PROGRESS\n",
        "# =========================================================\n",
        "\n",
        "st.write(\"\")\n",
        "\n",
        "question_number = st.session_state.question_number\n",
        "\n",
        "st.write(\n",
        "    f\"### Question {question_number} of 10\"\n",
        ")\n",
        "\n",
        "st.progress(\n",
        "    question_number / 10\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# QUESTION\n",
        "# =========================================================\n",
        "\n",
        "st.markdown(\n",
        "    f\"\"\"\n",
        "    <div class=\"question-card\">\n",
        "        <div class=\"big-question\">\n",
        "            {st.session_state.question} = ?\n",
        "        </div>\n",
        "    </div>\n",
        "    \"\"\",\n",
        "    unsafe_allow_html=True\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# ANSWERS\n",
        "# =========================================================\n",
        "\n",
        "if not st.session_state.answered:\n",
        "\n",
        "    st.subheader(\"🎯 Choose your answer\")\n",
        "\n",
        "    options = st.session_state.options\n",
        "\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "\n",
        "        if st.button(\n",
        "            f\"🔵 {options[0]}\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "\n",
        "            selected = options[0]\n",
        "\n",
        "            if selected == st.session_state.correct_answer:\n",
        "\n",
        "                st.session_state.score += 100\n",
        "                st.session_state.xp += 50\n",
        "                st.session_state.correct += 1\n",
        "                st.session_state.streak += 1\n",
        "\n",
        "                if st.session_state.streak > st.session_state.best_streak:\n",
        "                    st.session_state.best_streak = st.session_state.streak\n",
        "\n",
        "                st.session_state.feedback = \"correct\"\n",
        "\n",
        "            else:\n",
        "\n",
        "                st.session_state.wrong += 1\n",
        "                st.session_state.lives -= 1\n",
        "                st.session_state.streak = 0\n",
        "\n",
        "                st.session_state.feedback = \"wrong\"\n",
        "\n",
        "            st.session_state.selected_answer = selected\n",
        "            st.session_state.answered = True\n",
        "\n",
        "            st.rerun()\n",
        "\n",
        "        if st.button(\n",
        "            f\"🟢 {options[1]}\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "\n",
        "            selected = options[1]\n",
        "\n",
        "            if selected == st.session_state.correct_answer:\n",
        "\n",
        "                st.session_state.score += 100\n",
        "                st.session_state.xp += 50\n",
        "                st.session_state.correct += 1\n",
        "                st.session_state.streak += 1\n",
        "\n",
        "                if st.session_state.streak > st.session_state.best_streak:\n",
        "                    st.session_state.best_streak = st.session_state.streak\n",
        "\n",
        "                st.session_state.feedback = \"correct\"\n",
        "\n",
        "            else:\n",
        "\n",
        "                st.session_state.wrong += 1\n",
        "                st.session_state.lives -= 1\n",
        "                st.session_state.streak = 0\n",
        "\n",
        "                st.session_state.feedback = \"wrong\"\n",
        "\n",
        "            st.session_state.selected_answer = selected\n",
        "            st.session_state.answered = True\n",
        "\n",
        "            st.rerun()\n",
        "\n",
        "    with col2:\n",
        "\n",
        "        if st.button(\n",
        "            f\"🟡 {options[2]}\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "\n",
        "            selected = options[2]\n",
        "\n",
        "            if selected == st.session_state.correct_answer:\n",
        "\n",
        "                st.session_state.score += 100\n",
        "                st.session_state.xp += 50\n",
        "                st.session_state.correct += 1\n",
        "                st.session_state.streak += 1\n",
        "\n",
        "                if st.session_state.streak > st.session_state.best_streak:\n",
        "                    st.session_state.best_streak = st.session_state.streak\n",
        "\n",
        "                st.session_state.feedback = \"correct\"\n",
        "\n",
        "            else:\n",
        "\n",
        "                st.session_state.wrong += 1\n",
        "                st.session_state.lives -= 1\n",
        "                st.session_state.streak = 0\n",
        "\n",
        "                st.session_state.feedback = \"wrong\"\n",
        "\n",
        "            st.session_state.selected_answer = selected\n",
        "            st.session_state.answered = True\n",
        "\n",
        "            st.rerun()\n",
        "\n",
        "        if st.button(\n",
        "            f\"🔴 {options[3]}\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "\n",
        "            selected = options[3]\n",
        "\n",
        "            if selected == st.session_state.correct_answer:\n",
        "\n",
        "                st.session_state.score += 100\n",
        "                st.session_state.xp += 50\n",
        "                st.session_state.correct += 1\n",
        "                st.session_state.streak += 1\n",
        "\n",
        "                if st.session_state.streak > st.session_state.best_streak:\n",
        "                    st.session_state.best_streak = st.session_state.streak\n",
        "\n",
        "                st.session_state.feedback = \"correct\"\n",
        "\n",
        "            else:\n",
        "\n",
        "                st.session_state.wrong += 1\n",
        "                st.session_state.lives -= 1\n",
        "                st.session_state.streak = 0\n",
        "\n",
        "                st.session_state.feedback = \"wrong\"\n",
        "\n",
        "            st.session_state.selected_answer = selected\n",
        "            st.session_state.answered = True\n",
        "\n",
        "            st.rerun()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# FEEDBACK\n",
        "# =========================================================\n",
        "\n",
        "if st.session_state.answered:\n",
        "\n",
        "    st.write(\"\")\n",
        "\n",
        "    if st.session_state.feedback == \"correct\":\n",
        "\n",
        "        st.success(\n",
        "            \"🎉 CORRECT! Excellent work!\"\n",
        "        )\n",
        "\n",
        "        if st.session_state.streak >= 3:\n",
        "\n",
        "            st.info(\n",
        "                f\"🔥 {st.session_state.streak} answer streak!\"\n",
        "            )\n",
        "\n",
        "    else:\n",
        "\n",
        "        st.error(\n",
        "            f\"❌ Not quite. The correct answer is \"\n",
        "            f\"**{st.session_state.correct_answer}**.\"\n",
        "        )\n",
        "\n",
        "    st.write(\"\")\n",
        "\n",
        "    # Check lives\n",
        "\n",
        "    if st.session_state.lives <= 0:\n",
        "\n",
        "        st.warning(\n",
        "            \"💔 You have used all your lives!\"\n",
        "        )\n",
        "\n",
        "        if st.button(\n",
        "            \"🏁 SEE FINAL RESULT\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "\n",
        "            st.session_state.game_over = True\n",
        "            st.rerun()\n",
        "\n",
        "    elif st.session_state.question_number >= 10:\n",
        "\n",
        "        if st.button(\n",
        "            \"🏆 FINISH GAME\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "\n",
        "            st.session_state.game_over = True\n",
        "            st.rerun()\n",
        "\n",
        "    else:\n",
        "\n",
        "        if st.button(\n",
        "            \"➡️ NEXT QUESTION\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "\n",
        "            next_question()\n",
        "\n",
        "            st.rerun()\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# SIDEBAR\n",
        "# =========================================================\n",
        "\n",
        "with st.sidebar:\n",
        "\n",
        "    st.header(\"📊 Game Dashboard\")\n",
        "\n",
        "    st.write(\n",
        "        f\"**Topic:** {st.session_state.category}\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        f\"**Difficulty:** {st.session_state.difficulty}\"\n",
        "    )\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    st.write(\n",
        "        f\"⭐ Score: **{st.session_state.score}**\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        f\"🔥 Streak: **{st.session_state.streak}**\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        f\"🎯 Correct: **{st.session_state.correct}**\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        f\"❌ Wrong: **{st.session_state.wrong}**\"\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        f\"⚡ XP: **{st.session_state.xp}**\"\n",
        "    )\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    st.subheader(\"🏅 Achievements\")\n",
        "\n",
        "    if st.session_state.correct >= 3:\n",
        "        st.write(\"🎯 3 Correct Answers\")\n",
        "\n",
        "    if st.session_state.best_streak >= 3:\n",
        "        st.write(\"🔥 3 Answer Streak\")\n",
        "\n",
        "    if st.session_state.score >= 500:\n",
        "        st.write(\"⭐ 500 Points\")\n",
        "\n",
        "    st.divider()\n",
        "\n",
        "    st.caption(\n",
        "        \"Math Adventure\\n\"\n",
        "        \"Educational Game\"\n",
        "    )"
      ],
      "metadata": {
        "id": "O1_p8bTBSQ8i"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}