{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/genesiszaim-png/chatbot/blob/main/math_game.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import random\n",
        "\n",
        "# -----------------------------\n",
        "# PAGE SETTINGS\n",
        "# -----------------------------\n",
        "st.set_page_config(\n",
        "    page_title=\"Math Treasure Hunt\",\n",
        "    page_icon=\"🏆\"\n",
        ")\n",
        "\n",
        "# -----------------------------\n",
        "# GAME TITLE\n",
        "# -----------------------------\n",
        "st.title(\"🏆 Math Treasure Hunt\")\n",
        "st.write(\"Answer the questions and find the hidden treasure!\")\n",
        "st.write(\"You have 3 lives ❤️\")\n",
        "\n",
        "# -----------------------------\n",
        "# START / RESET GAME\n",
        "# -----------------------------\n",
        "if \"started\" not in st.session_state:\n",
        "    st.session_state.started = False\n",
        "\n",
        "if \"score\" not in st.session_state:\n",
        "    st.session_state.score = 0\n",
        "\n",
        "if \"lives\" not in st.session_state:\n",
        "    st.session_state.lives = 3\n",
        "\n",
        "if \"question\" not in st.session_state:\n",
        "    st.session_state.question = 1\n",
        "\n",
        "if \"a\" not in st.session_state:\n",
        "    st.session_state.a = random.randint(1, 10)\n",
        "\n",
        "if \"b\" not in st.session_state:\n",
        "    st.session_state.b = random.randint(1, 10)\n",
        "\n",
        "if \"operation\" not in st.session_state:\n",
        "    st.session_state.operation = random.choice([\"+\", \"-\", \"×\"])\n",
        "\n",
        "if \"message\" not in st.session_state:\n",
        "    st.session_state.message = \"\"\n",
        "\n",
        "# -----------------------------\n",
        "# FUNCTION TO CREATE QUESTION\n",
        "# -----------------------------\n",
        "def new_question():\n",
        "    st.session_state.a = random.randint(1, 10)\n",
        "    st.session_state.b = random.randint(1, 10)\n",
        "    st.session_state.operation = random.choice([\"+\", \"-\", \"×\"])\n",
        "\n",
        "\n",
        "# -----------------------------\n",
        "# START GAME\n",
        "# -----------------------------\n",
        "if not st.session_state.started:\n",
        "\n",
        "    st.subheader(\"Ready to play?\")\n",
        "\n",
        "    st.write(\"🎯 Your mission:\")\n",
        "    st.write(\"Answer 5 maths questions to find the treasure!\")\n",
        "\n",
        "    if st.button(\"🚀 START GAME\"):\n",
        "        st.session_state.started = True\n",
        "        st.rerun()\n",
        "\n",
        "# -----------------------------\n",
        "# GAME\n",
        "# -----------------------------\n",
        "else:\n",
        "\n",
        "    # Show score and lives\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "        st.metric(\"⭐ Score\", st.session_state.score)\n",
        "\n",
        "    with col2:\n",
        "        st.metric(\"❤️ Lives\", st.session_state.lives)\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "    # -------------------------\n",
        "    # GAME OVER\n",
        "    # -------------------------\n",
        "    if st.session_state.lives <= 0:\n",
        "\n",
        "        st.error(\"💀 GAME OVER!\")\n",
        "        st.write(\"You ran out of lives.\")\n",
        "\n",
        "        if st.button(\"🔄 PLAY AGAIN\"):\n",
        "            st.session_state.started = False\n",
        "            st.session_state.score = 0\n",
        "            st.session_state.lives = 3\n",
        "            st.session_state.question = 1\n",
        "            st.session_state.message = \"\"\n",
        "            new_question()\n",
        "            st.rerun()\n",
        "\n",
        "    # -------------------------\n",
        "    # WIN\n",
        "    # -------------------------\n",
        "    elif st.session_state.question > 5:\n",
        "\n",
        "        st.success(\"🎉 YOU FOUND THE TREASURE!\")\n",
        "        st.balloons()\n",
        "\n",
        "        st.write(\"🏆 Final Score:\", st.session_state.score)\n",
        "\n",
        "        if st.session_state.score >= 40:\n",
        "            st.write(\"🌟 Amazing! You are a Math Master!\")\n",
        "        elif st.session_state.score >= 30:\n",
        "            st.write(\"👏 Great job!\")\n",
        "        else:\n",
        "            st.write(\"👍 Good effort! Keep practising!\")\n",
        "\n",
        "        if st.button(\"🔄 PLAY AGAIN\"):\n",
        "            st.session_state.started = False\n",
        "            st.session_state.score = 0\n",
        "            st.session_state.lives = 3\n",
        "            st.session_state.question = 1\n",
        "            st.session_state.message = \"\"\n",
        "            new_question()\n",
        "            st.rerun()\n",
        "\n",
        "    # -------------------------\n",
        "    # QUESTION\n",
        "    # -------------------------\n",
        "    else:\n",
        "\n",
        "        st.subheader(\n",
        "            f\"Question {st.session_state.question} of 5\"\n",
        "        )\n",
        "\n",
        "        a = st.session_state.a\n",
        "        b = st.session_state.b\n",
        "        operation = st.session_state.operation\n",
        "\n",
        "        # Make sure subtraction does not give a negative answer\n",
        "        if operation == \"-\" and a < b:\n",
        "            a, b = b, a\n",
        "            st.session_state.a = a\n",
        "            st.session_state.b = b\n",
        "\n",
        "        # Calculate correct answer\n",
        "        if operation == \"+\":\n",
        "            correct_answer = a + b\n",
        "\n",
        "        elif operation == \"-\":\n",
        "            correct_answer = a - b\n",
        "\n",
        "        else:\n",
        "            correct_answer = a * b\n",
        "\n",
        "        # Display question\n",
        "        st.write(f\"### What is {a} {operation} {b}?\")\n",
        "\n",
        "        # Student answer\n",
        "        answer = st.number_input(\n",
        "            \"Enter your answer:\",\n",
        "            min_value=0,\n",
        "            step=1,\n",
        "            key=f\"answer_{st.session_state.question}\"\n",
        "        )\n",
        "\n",
        "        # Submit button\n",
        "        if st.button(\"✅ SUBMIT ANSWER\"):\n",
        "\n",
        "            if answer == correct_answer:\n",
        "\n",
        "                st.session_state.score += 10\n",
        "\n",
        "                st.session_state.message = (\n",
        "                    \"🎉 Correct! You earned 10 points!\"\n",
        "                )\n",
        "\n",
        "                st.session_state.question += 1\n",
        "\n",
        "                new_question()\n",
        "\n",
        "                st.rerun()\n",
        "\n",
        "            else:\n",
        "\n",
        "                st.session_state.lives -= 1\n",
        "\n",
        "                st.session_state.message = (\n",
        "                    f\"❌ Not quite! The correct answer was \"\n",
        "                    f\"{correct_answer}.\"\n",
        "                )\n",
        "\n",
        "                st.rerun()\n",
        "\n",
        "        # Show feedback\n",
        "        if st.session_state.message:\n",
        "            st.info(st.session_state.message)"
      ],
      "metadata": {
        "id": "W2dyVGdsRvP_"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}