{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMEA0T45xeOJsvlFHMVGB3g",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/genesiszaim-png/chatbot/blob/main/new_math_game.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import random\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# PAGE CONFIGURATION\n",
        "# ---------------------------------------------------------\n",
        "st.set_page_config(\n",
        "    page_title=\"Math Challenge\",\n",
        "    page_icon=\"🧮\",\n",
        "    layout=\"centered\"\n",
        ")\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# CUSTOM CSS\n",
        "# ---------------------------------------------------------\n",
        "st.markdown(\"\"\"\n",
        "<style>\n",
        "    .main-title {\n",
        "        text-align: center;\n",
        "        font-size: 42px;\n",
        "        font-weight: bold;\n",
        "        margin-bottom: 5px;\n",
        "    }\n",
        "\n",
        "    .subtitle {\n",
        "        text-align: center;\n",
        "        font-size: 20px;\n",
        "        margin-bottom: 25px;\n",
        "    }\n",
        "\n",
        "    .question-box {\n",
        "        padding: 25px;\n",
        "        border-radius: 15px;\n",
        "        border: 2px solid #ddd;\n",
        "        margin-bottom: 20px;\n",
        "        text-align: center;\n",
        "    }\n",
        "\n",
        "    .score-box {\n",
        "        padding: 20px;\n",
        "        border-radius: 15px;\n",
        "        text-align: center;\n",
        "        border: 2px solid #ddd;\n",
        "        margin-top: 20px;\n",
        "    }\n",
        "</style>\n",
        "\"\"\", unsafe_allow_html=True)\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# GAME FUNCTIONS\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "def generate_question():\n",
        "    \"\"\"Generate a random mathematics question.\"\"\"\n",
        "\n",
        "    operation = random.choice([\"+\", \"-\", \"×\", \"÷\"])\n",
        "\n",
        "    if operation == \"+\":\n",
        "        a = random.randint(1, 50)\n",
        "        b = random.randint(1, 50)\n",
        "\n",
        "        question = f\"{a} + {b} = ?\"\n",
        "        answer = a + b\n",
        "\n",
        "    elif operation == \"-\":\n",
        "        a = random.randint(10, 50)\n",
        "        b = random.randint(1, a)\n",
        "\n",
        "        question = f\"{a} - {b} = ?\"\n",
        "        answer = a - b\n",
        "\n",
        "    elif operation == \"×\":\n",
        "        a = random.randint(2, 12)\n",
        "        b = random.randint(2, 12)\n",
        "\n",
        "        question = f\"{a} × {b} = ?\"\n",
        "        answer = a * b\n",
        "\n",
        "    else:\n",
        "        # Create division questions with whole-number answers\n",
        "        b = random.randint(2, 12)\n",
        "        answer = random.randint(2, 12)\n",
        "        a = b * answer\n",
        "\n",
        "        question = f\"{a} ÷ {b} = ?\"\n",
        "\n",
        "    return question, answer\n",
        "\n",
        "\n",
        "def create_options(correct_answer):\n",
        "    \"\"\"Create four multiple-choice options.\"\"\"\n",
        "\n",
        "    options = {correct_answer}\n",
        "\n",
        "    while len(options) < 4:\n",
        "        variation = random.randint(-10, 10)\n",
        "\n",
        "        if variation == 0:\n",
        "            continue\n",
        "\n",
        "        new_option = correct_answer + variation\n",
        "\n",
        "        if new_option >= 0:\n",
        "            options.add(new_option)\n",
        "\n",
        "    options = list(options)\n",
        "    random.shuffle(options)\n",
        "\n",
        "    return options\n",
        "\n",
        "\n",
        "def start_game():\n",
        "    \"\"\"Start or restart the game.\"\"\"\n",
        "\n",
        "    st.session_state.question_number = 1\n",
        "    st.session_state.score = 0\n",
        "    st.session_state.game_over = False\n",
        "    st.session_state.answered = False\n",
        "\n",
        "    question, answer = generate_question()\n",
        "\n",
        "    st.session_state.question = question\n",
        "    st.session_state.correct_answer = answer\n",
        "    st.session_state.options = create_options(answer)\n",
        "\n",
        "\n",
        "def next_question():\n",
        "    \"\"\"Generate the next question.\"\"\"\n",
        "\n",
        "    st.session_state.question_number += 1\n",
        "    st.session_state.answered = False\n",
        "\n",
        "    question, answer = generate_question()\n",
        "\n",
        "    st.session_state.question = question\n",
        "    st.session_state.correct_answer = answer\n",
        "    st.session_state.options = create_options(answer)\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# INITIALIZE GAME\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "if \"question_number\" not in st.session_state:\n",
        "    start_game()\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# TITLE\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "st.markdown(\n",
        "    '<div class=\"main-title\">🧮 MATH CHALLENGE</div>',\n",
        "    unsafe_allow_html=True\n",
        ")\n",
        "\n",
        "st.markdown(\n",
        "    '<div class=\"subtitle\">Can you get all 10 questions correct?</div>',\n",
        "    unsafe_allow_html=True\n",
        ")\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# GAME OVER SCREEN\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "if st.session_state.game_over:\n",
        "\n",
        "    score = st.session_state.score\n",
        "\n",
        "    st.success(\"🎉 GAME COMPLETE!\")\n",
        "\n",
        "    st.markdown(\n",
        "        f\"\"\"\n",
        "        <div class=\"score-box\">\n",
        "            <h1>🏆 Your Score</h1>\n",
        "            <h2>{score} / 10</h2>\n",
        "        </div>\n",
        "        \"\"\",\n",
        "        unsafe_allow_html=True\n",
        "    )\n",
        "\n",
        "    percentage = score * 10\n",
        "\n",
        "    if percentage == 100:\n",
        "        st.balloons()\n",
        "        st.success(\"🌟 Perfect! You are a Math Master!\")\n",
        "\n",
        "    elif percentage >= 80:\n",
        "        st.success(\"👏 Excellent work!\")\n",
        "\n",
        "    elif percentage >= 60:\n",
        "        st.info(\"👍 Good job! Keep practising!\")\n",
        "\n",
        "    elif percentage >= 40:\n",
        "        st.warning(\"💪 Nice try! A little more practice will help!\")\n",
        "\n",
        "    else:\n",
        "        st.error(\"📚 Keep practising. You can do it!\")\n",
        "\n",
        "    st.write(\"\")\n",
        "\n",
        "    if st.button(\"🔄 PLAY AGAIN\", use_container_width=True):\n",
        "        start_game()\n",
        "        st.rerun()\n",
        "\n",
        "    st.stop()\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# GAME INFORMATION\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "st.write(\n",
        "    f\"### Question {st.session_state.question_number} of 10\"\n",
        ")\n",
        "\n",
        "progress = st.session_state.question_number / 10\n",
        "\n",
        "st.progress(progress)\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# QUESTION\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "st.markdown(\n",
        "    f\"\"\"\n",
        "    <div class=\"question-box\">\n",
        "        <h1>{st.session_state.question}</h1>\n",
        "    </div>\n",
        "    \"\"\",\n",
        "    unsafe_allow_html=True\n",
        ")\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# ANSWER BUTTONS\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "if not st.session_state.answered:\n",
        "\n",
        "    st.write(\"### Choose your answer:\")\n",
        "\n",
        "    options = st.session_state.options\n",
        "\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "\n",
        "        if st.button(\n",
        "            f\"🔵 {options[0]}\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "            if options[0] == st.session_state.correct_answer:\n",
        "                st.session_state.score += 1\n",
        "                st.session_state.feedback = \"correct\"\n",
        "            else:\n",
        "                st.session_state.feedback = \"wrong\"\n",
        "\n",
        "            st.session_state.selected_answer = options[0]\n",
        "            st.session_state.answered = True\n",
        "            st.rerun()\n",
        "\n",
        "        if st.button(\n",
        "            f\"🟢 {options[1]}\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "            if options[1] == st.session_state.correct_answer:\n",
        "                st.session_state.score += 1\n",
        "                st.session_state.feedback = \"correct\"\n",
        "            else:\n",
        "                st.session_state.feedback = \"wrong\"\n",
        "\n",
        "            st.session_state.selected_answer = options[1]\n",
        "            st.session_state.answered = True\n",
        "            st.rerun()\n",
        "\n",
        "    with col2:\n",
        "\n",
        "        if st.button(\n",
        "            f\"🟡 {options[2]}\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "            if options[2] == st.session_state.correct_answer:\n",
        "                st.session_state.score += 1\n",
        "                st.session_state.feedback = \"correct\"\n",
        "            else:\n",
        "                st.session_state.feedback = \"wrong\"\n",
        "\n",
        "            st.session_state.selected_answer = options[2]\n",
        "            st.session_state.answered = True\n",
        "            st.rerun()\n",
        "\n",
        "        if st.button(\n",
        "            f\"🔴 {options[3]}\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "            if options[3] == st.session_state.correct_answer:\n",
        "                st.session_state.score += 1\n",
        "                st.session_state.feedback = \"correct\"\n",
        "            else:\n",
        "                st.session_state.feedback = \"wrong\"\n",
        "\n",
        "            st.session_state.selected_answer = options[3]\n",
        "            st.session_state.answered = True\n",
        "            st.rerun()\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# FEEDBACK\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "if st.session_state.answered:\n",
        "\n",
        "    if st.session_state.feedback == \"correct\":\n",
        "\n",
        "        st.success(\"✅ Correct! Well done!\")\n",
        "\n",
        "    else:\n",
        "\n",
        "        st.error(\n",
        "            f\"❌ Not quite. The correct answer is \"\n",
        "            f\"**{st.session_state.correct_answer}**.\"\n",
        "        )\n",
        "\n",
        "    st.write(\"\")\n",
        "\n",
        "    if st.session_state.question_number < 10:\n",
        "\n",
        "        if st.button(\n",
        "            \"➡️ NEXT QUESTION\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "            next_question()\n",
        "            st.rerun()\n",
        "\n",
        "    else:\n",
        "\n",
        "        if st.button(\n",
        "            \"🏁 SEE MY SCORE\",\n",
        "            use_container_width=True\n",
        "        ):\n",
        "            st.session_state.game_over = True\n",
        "            st.rerun()\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# SCORE\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "st.write(\"\")\n",
        "\n",
        "st.markdown(\n",
        "    f\"\"\"\n",
        "    <div class=\"score-box\">\n",
        "        <h3>⭐ Current Score: {st.session_state.score}</h3>\n",
        "    </div>\n",
        "    \"\"\",\n",
        "    unsafe_allow_html=True\n",
        ")\n",
        "\n",
        "st.write(\"\")\n",
        "\n",
        "st.caption(\n",
        "    \"🧮 Math Challenge • Created for educational purposes\"\n",
        ")"
      ],
      "metadata": {
        "id": "uYcK56MhPzOh"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}