{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/genesiszaim-png/chatbot/blob/main/science_game.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "\n",
        "# ==========================================\n",
        "# SCIENCE QUEST\n",
        "# Year 5 Science Game\n",
        "# ==========================================\n",
        "\n",
        "st.set_page_config(\n",
        "    page_title=\"Science Quest\",\n",
        "    page_icon=\"🔬\",\n",
        "    layout=\"centered\"\n",
        ")\n",
        "\n",
        "# ==========================================\n",
        "# GAME DATA\n",
        "# ==========================================\n",
        "\n",
        "levels = {\n",
        "    1: {\n",
        "        \"name\": \"🌱 LEVEL 1: LIVING THINGS\",\n",
        "        \"questions\": [\n",
        "            {\n",
        "                \"question\": \"Which organ do humans use to pump blood around the body?\",\n",
        "                \"options\": [\"Lungs\", \"Heart\", \"Brain\", \"Stomach\"],\n",
        "                \"answer\": \"Heart\"\n",
        "            },\n",
        "            {\n",
        "                \"question\": \"Which of these is needed by plants to make food?\",\n",
        "                \"options\": [\"Sunlight\", \"Plastic\", \"Salt\", \"Oil\"],\n",
        "                \"answer\": \"Sunlight\"\n",
        "            },\n",
        "            {\n",
        "                \"question\": \"Which animal is a mammal?\",\n",
        "                \"options\": [\"Frog\", \"Eagle\", \"Dolphin\", \"Butterfly\"],\n",
        "                \"answer\": \"Dolphin\"\n",
        "            },\n",
        "            {\n",
        "                \"question\": \"Which part of a plant absorbs water from the soil?\",\n",
        "                \"options\": [\"Flower\", \"Leaf\", \"Root\", \"Fruit\"],\n",
        "                \"answer\": \"Root\"\n",
        "            }\n",
        "        ]\n",
        "    },\n",
        "\n",
        "    2: {\n",
        "        \"name\": \"⚡ LEVEL 2: ENERGY & MATTER\",\n",
        "        \"questions\": [\n",
        "            {\n",
        "                \"question\": \"Which form of energy allows us to see objects?\",\n",
        "                \"options\": [\"Sound energy\", \"Light energy\",\n",
        "                           \"Heat energy\", \"Chemical energy\"],\n",
        "                \"answer\": \"Light energy\"\n",
        "            },\n",
        "            {\n",
        "                \"question\": \"What happens to ice when it is heated?\",\n",
        "                \"options\": [\"It freezes\", \"It melts\",\n",
        "                           \"It disappears immediately\", \"It becomes heavier\"],\n",
        "                \"answer\": \"It melts\"\n",
        "            },\n",
        "            {\n",
        "                \"question\": \"Which material is a good conductor of electricity?\",\n",
        "                \"options\": [\"Rubber\", \"Wood\", \"Copper\", \"Plastic\"],\n",
        "                \"answer\": \"Copper\"\n",
        "            }\n",
        "        ]\n",
        "    },\n",
        "\n",
        "    3: {\n",
        "        \"name\": \"🌍 LEVEL 3: EARTH & SPACE\",\n",
        "        \"questions\": [\n",
        "            {\n",
        "                \"question\": \"What causes day and night on Earth?\",\n",
        "                \"options\": [\n",
        "                    \"The Moon moving around Earth\",\n",
        "                    \"Earth rotating on its axis\",\n",
        "                    \"The Sun moving around Earth\",\n",
        "                    \"Clouds moving across the sky\"\n",
        "                ],\n",
        "                \"answer\": \"Earth rotating on its axis\"\n",
        "            },\n",
        "            {\n",
        "                \"question\": \"Which planet is known as the Red Planet?\",\n",
        "                \"options\": [\"Venus\", \"Mars\", \"Jupiter\", \"Saturn\"],\n",
        "                \"answer\": \"Mars\"\n",
        "            },\n",
        "            {\n",
        "                \"question\": \"What is the main source of energy for Earth?\",\n",
        "                \"options\": [\"The Moon\", \"The Sun\", \"The ocean\", \"The wind\"],\n",
        "                \"answer\": \"The Sun\"\n",
        "            }\n",
        "        ]\n",
        "    }\n",
        "}\n",
        "\n",
        "# ==========================================\n",
        "# SESSION STATE\n",
        "# ==========================================\n",
        "\n",
        "if \"game_started\" not in st.session_state:\n",
        "    st.session_state.game_started = False\n",
        "\n",
        "if \"level\" not in st.session_state:\n",
        "    st.session_state.level = 1\n",
        "\n",
        "if \"question_number\" not in st.session_state:\n",
        "    st.session_state.question_number = 0\n",
        "\n",
        "if \"score\" not in st.session_state:\n",
        "    st.session_state.score = 0\n",
        "\n",
        "if \"lives\" not in st.session_state:\n",
        "    st.session_state.lives = 3\n",
        "\n",
        "if \"message\" not in st.session_state:\n",
        "    st.session_state.message = \"\"\n",
        "\n",
        "if \"game_over\" not in st.session_state:\n",
        "    st.session_state.game_over = False\n",
        "\n",
        "if \"finished\" not in st.session_state:\n",
        "    st.session_state.finished = False\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# RESET GAME\n",
        "# ==========================================\n",
        "\n",
        "def reset_game():\n",
        "    st.session_state.game_started = False\n",
        "    st.session_state.level = 1\n",
        "    st.session_state.question_number = 0\n",
        "    st.session_state.score = 0\n",
        "    st.session_state.lives = 3\n",
        "    st.session_state.message = \"\"\n",
        "    st.session_state.game_over = False\n",
        "    st.session_state.finished = False\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# TITLE SCREEN\n",
        "# ==========================================\n",
        "\n",
        "if not st.session_state.game_started:\n",
        "\n",
        "    st.title(\"🔬 SCIENCE QUEST\")\n",
        "    st.subheader(\"🌍 The Year 5 Science Adventure\")\n",
        "\n",
        "    st.write(\n",
        "        \"Welcome, young scientist! Your mission is to complete \"\n",
        "        \"3 science levels and become a Science Master.\"\n",
        "    )\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "    st.markdown(\"\"\"\n",
        "    ### 🎮 GAME RULES\n",
        "\n",
        "    ❤️ You start with **3 lives**\n",
        "\n",
        "    ⭐ Correct answer = **10 points**\n",
        "\n",
        "    ❌ Wrong answer = **lose 1 life**\n",
        "\n",
        "    🔓 Complete each level to unlock the next one\n",
        "\n",
        "    🏆 Complete all 3 levels to become a **Science Master!**\n",
        "    \"\"\")\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "    st.info(\n",
        "        \"There are 10 questions in total. \"\n",
        "        \"Think carefully before answering!\"\n",
        "    )\n",
        "\n",
        "    if st.button(\"🚀 START SCIENCE QUEST\", use_container_width=True):\n",
        "        st.session_state.game_started = True\n",
        "        st.rerun()\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# GAME OVER\n",
        "# ==========================================\n",
        "\n",
        "elif st.session_state.game_over:\n",
        "\n",
        "    st.title(\"💥 GAME OVER!\")\n",
        "\n",
        "    st.error(\"You have used all your lives.\")\n",
        "\n",
        "    st.write(f\"⭐ Your final score: **{st.session_state.score}**\")\n",
        "\n",
        "    st.write(\n",
        "        \"Don't give up! Scientists learn by asking questions, \"\n",
        "        \"testing ideas and trying again.\"\n",
        "    )\n",
        "\n",
        "    if st.button(\"🔄 TRY AGAIN\", use_container_width=True):\n",
        "        reset_game()\n",
        "        st.rerun()\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# FINISHED GAME\n",
        "# ==========================================\n",
        "\n",
        "elif st.session_state.finished:\n",
        "\n",
        "    st.title(\"🏆 SCIENCE MASTER!\")\n",
        "\n",
        "    st.balloons()\n",
        "\n",
        "    st.success(\n",
        "        \"Congratulations! You completed all 3 levels!\"\n",
        "    )\n",
        "\n",
        "    st.metric(\n",
        "        \"FINAL SCORE\",\n",
        "        f\"{st.session_state.score} / 100\"\n",
        "    )\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "    if st.session_state.score == 100:\n",
        "        st.subheader(\"🌟 PERFECT SCORE!\")\n",
        "        st.write(\"You are an AMAZING Science Master!\")\n",
        "\n",
        "    elif st.session_state.score >= 80:\n",
        "        st.subheader(\"🥇 EXCELLENT!\")\n",
        "        st.write(\"You have excellent science knowledge!\")\n",
        "\n",
        "    elif st.session_state.score >= 60:\n",
        "        st.subheader(\"🥈 GREAT JOB!\")\n",
        "        st.write(\"You are becoming a strong young scientist!\")\n",
        "\n",
        "    else:\n",
        "        st.subheader(\"🥉 GOOD EFFORT!\")\n",
        "        st.write(\"Keep practising and discover more science!\")\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "    if st.button(\"🔄 PLAY AGAIN\", use_container_width=True):\n",
        "        reset_game()\n",
        "        st.rerun()\n",
        "\n",
        "\n",
        "# ==========================================\n",
        "# MAIN GAME\n",
        "# ==========================================\n",
        "\n",
        "else:\n",
        "\n",
        "    # --------------------------------------\n",
        "    # GAME HEADER\n",
        "    # --------------------------------------\n",
        "\n",
        "    current_level = st.session_state.level\n",
        "\n",
        "    level_data = levels[current_level]\n",
        "\n",
        "    st.title(\"🔬 SCIENCE QUEST\")\n",
        "\n",
        "    st.subheader(level_data[\"name\"])\n",
        "\n",
        "    # Score and lives\n",
        "    col1, col2, col3 = st.columns(3)\n",
        "\n",
        "    with col1:\n",
        "        st.metric(\n",
        "            \"⭐ SCORE\",\n",
        "            st.session_state.score\n",
        "        )\n",
        "\n",
        "    with col2:\n",
        "        st.metric(\n",
        "            \"❤️ LIVES\",\n",
        "            st.session_state.lives\n",
        "        )\n",
        "\n",
        "    with col3:\n",
        "        st.metric(\n",
        "            \"🎯 LEVEL\",\n",
        "            current_level\n",
        "        )\n",
        "\n",
        "    st.write(\"---\")\n",
        "\n",
        "    # --------------------------------------\n",
        "    # CURRENT QUESTION\n",
        "    # --------------------------------------\n",
        "\n",
        "    question_index = st.session_state.question_number\n",
        "\n",
        "    question_data = level_data[\"questions\"][question_index]\n",
        "\n",
        "    total_questions = 10\n",
        "\n",
        "    questions_completed = 0\n",
        "\n",
        "    for i in range(1, current_level):\n",
        "        questions_completed += len(levels[i][\"questions\"])\n",
        "\n",
        "    questions_completed += question_index\n",
        "\n",
        "    st.progress(\n",
        "        questions_completed / total_questions\n",
        "    )\n",
        "\n",
        "    st.write(\n",
        "        f\"Question {questions_completed + 1} \"\n",
        "        f\"of {total_questions}\"\n",
        "    )\n",
        "\n",
        "    st.markdown(\n",
        "        f\"### 🧠 {question_data['question']}\"\n",
        "    )\n",
        "\n",
        "    # --------------------------------------\n",
        "    # ANSWER\n",
        "    # --------------------------------------\n",
        "\n",
        "    answer = st.radio(\n",
        "        \"Choose your answer:\",\n",
        "        question_data[\"options\"],\n",
        "        key=f\"answer_{current_level}_{question_index}\"\n",
        "    )\n",
        "\n",
        "    # --------------------------------------\n",
        "    # SUBMIT\n",
        "    # --------------------------------------\n",
        "\n",
        "    if st.button(\n",
        "        \"🚀 SUBMIT ANSWER\",\n",
        "        use_container_width=True\n",
        "    ):\n",
        "\n",
        "        if answer == question_data[\"answer\"]:\n",
        "\n",
        "            st.session_state.score += 10\n",
        "\n",
        "            st.success(\n",
        "                \"🎉 CORRECT! Excellent science thinking!\"\n",
        "            )\n",
        "\n",
        "            st.session_state.question_number += 1\n",
        "\n",
        "            # --------------------------------\n",
        "            # END OF CURRENT LEVEL\n",
        "            # --------------------------------\n",
        "\n",
        "            if (\n",
        "                st.session_state.question_number\n",
        "                >= len(level_data[\"questions\"])\n",
        "            ):\n",
        "\n",
        "                # If Level 3 is complete\n",
        "                if current_level == 3:\n",
        "\n",
        "                    st.session_state.finished = True\n",
        "\n",
        "                else:\n",
        "\n",
        "                    st.session_state.level += 1\n",
        "\n",
        "                    st.session_state.question_number = 0\n",
        "\n",
        "                    st.balloons()\n",
        "\n",
        "                    st.info(\n",
        "                        f\"🔓 LEVEL {current_level + 1} UNLOCKED!\"\n",
        "                    )\n",
        "\n",
        "            st.rerun()\n",
        "\n",
        "        else:\n",
        "\n",
        "            st.session_state.lives -= 1\n",
        "\n",
        "            st.error(\n",
        "                \"❌ Incorrect!\"\n",
        "            )\n",
        "\n",
        "            st.write(\n",
        "                f\"💡 The correct answer is: \"\n",
        "                f\"**{question_data['answer']}**\"\n",
        "            )\n",
        "\n",
        "            if st.session_state.lives <= 0:\n",
        "\n",
        "                st.session_state.game_over = True\n",
        "\n",
        "            st.rerun()"
      ],
      "metadata": {
        "id": "ShmCAbvRUoVs"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}