{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "name": "science quiz",
      "authorship_tag": "ABX9TyMf+XNrfXARb12gpgQvfxYu",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/genesiszaim-png/chatbot/blob/main/science_quiz.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "\n",
        "# Set page layout and title\n",
        "st.set_page_config(page_title=\"Year 5 Science Quiz\", page_icon=\"🔬\")\n",
        "\n",
        "# Define Year 5 Science Questions\n",
        "QUESTIONS = [\n",
        "    {\n",
        "        \"question\": \"Which of the following is a primary producer in a food chain?\",\n",
        "        \"options\": [\"Lion\", \"Grasshopper\", \"Oak Tree\", \"Fungi\"],\n",
        "        \"answer\": \"Oak Tree\",\n",
        "        \"explanation\": \"Plants like oak trees make their own food through photosynthesis, making them primary producers.\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"What process occurs when liquid water turns into water vapor?\",\n",
        "        \"options\": [\"Condensation\", \"Evaporation\", \"Precipitation\", \"Freezing\"],\n",
        "        \"answer\": \"Evaporation\",\n",
        "        \"explanation\": \"Evaporation is the process where heat turns liquid water into gas (water vapor).\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"How long does it take for Earth to complete one full rotation on its axis?\",\n",
        "        \"options\": [\"365 days\", \"28 days\", \"24 hours\", \"12 hours\"],\n",
        "        \"answer\": \"24 hours\",\n",
        "        \"explanation\": \"Earth takes about 24 hours to spin once on its axis, causing day and night.\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"Which state of matter has a fixed volume but takes the shape of its container?\",\n",
        "        \"options\": [\"Solid\", \"Liquid\", \"Gas\", \"Plasma\"],\n",
        "        \"answer\": \"Liquid\",\n",
        "        \"explanation\": \"Liquids keep the same volume but flow to fit the shape of the container they are in.\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"Which part of a flower attracts insects for pollination?\",\n",
        "        \"options\": [\"Roots\", \"Petals\", \"Stem\", \"Sepal\"],\n",
        "        \"answer\": \"Petals\",\n",
        "        \"explanation\": \"Brightly colored petals and scents attract insects like bees and butterflies.\"\n",
        "    }\n",
        "]\n",
        "\n",
        "# Initialize Session State Variables\n",
        "if \"current_q\" not in st.session_state:\n",
        "    st.session_state.current_q = 0\n",
        "if \"score\" not in st.session_state:\n",
        "    st.session_state.score = 0\n",
        "if \"quiz_finished\" not in st.session_state:\n",
        "    st.session_state.quiz_finished = False\n",
        "if \"answered\" not in st.session_state:\n",
        "    st.session_state.answered = False\n",
        "\n",
        "# Function to restart the quiz\n",
        "def restart_quiz():\n",
        "    st.session_state.current_q = 0\n",
        "    st.session_state.score = 0\n",
        "    st.session_state.quiz_finished = False\n",
        "    st.session_state.answered = False\n",
        "\n",
        "# Streamlit App UI\n",
        "st.title(\"🔬 Year 5 Science Quiz\")\n",
        "st.write(\"Test your knowledge on life processes, space, water cycles, and states of matter!\")\n",
        "\n",
        "if not st.session_state.quiz_finished:\n",
        "    current_idx = st.session_state.current_q\n",
        "    q_data = QUESTIONS[current_idx]\n",
        "\n",
        "    # Display Progress\n",
        "    st.progress((current_idx) / len(QUESTIONS))\n",
        "    st.subheader(f\"Question {current_idx + 1} of {len(QUESTIONS)}\")\n",
        "    st.write(f\"**{q_data['question']}**\")\n",
        "\n",
        "    # Selection Form\n",
        "    with st.form(key=f\"q_form_{current_idx}\"):\n",
        "        user_choice = st.radio(\"Choose your answer:\", q_data[\"options\"], key=f\"radio_{current_idx}\")\n",
        "        submit_button = st.form_submit_button(label=\"Submit Answer\")\n",
        "\n",
        "        if submit_button:\n",
        "            st.session_state.answered = True\n",
        "            if user_choice == q_data[\"answer\"]:\n",
        "                st.session_state.score += 1\n",
        "                st.success(\"🎉 Correct!\")\n",
        "            else:\n",
        "                st.error(f\"❌ Incorrect! The correct answer was: **{q_data['answer']}**\")\n",
        "\n",
        "            st.info(f\"💡 **Explanation:** {q_data['explanation']}\")\n",
        "\n",
        "    # Next Question Navigation\n",
        "    if st.session_state.answered:\n",
        "        if current_idx + 1 < len(QUESTIONS):\n",
        "            if st.button(\"Next Question ➔\"):\n",
        "                st.session_state.current_q += 1\n",
        "                st.session_state.answered = False\n",
        "                st.rerun()\n",
        "        else:\n",
        "            if st.button(\"See Final Score 🏆\"):\n",
        "                st.session_state.quiz_finished = True\n",
        "                st.rerun()\n",
        "\n",
        "else:\n",
        "    # Final Results Screen\n",
        "    st.balloons()\n",
        "    st.subheader(\"Quiz Completed!\")\n",
        "    final_score = st.session_state.score\n",
        "    total_questions = len(QUESTIONS)\n",
        "    percentage = (final_score / total_questions) * 100\n",
        "\n",
        "    st.metric(label=\"Your Final Score\", value=f\"{final_score} / {total_questions}\", delta=f\"{percentage:.0f}%\")\n",
        "\n",
        "    if percentage == 100:\n",
        "        st.success(\"🌟 Perfect score! You are a Year 5 Science Superstar!\")\n",
        "    elif percentage >= 60:\n",
        "        st.info(\"👍 Great effort! You know your science well.\")\n",
        "    else:\n",
        "        st.warning(\"📚 Keep practicing! Review the topics and try again.\")\n",
        "\n",
        "    st.button(\"Restart Quiz\", on_click=restart_quiz)"
      ],
      "metadata": {
        "id": "z8WK3K6CjUYv"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}