{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/genesiszaim-png/chatbot/blob/main/testing.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Designing Mathematics Games with Python & Generative AI From Game Logic → Python → Play → Improve Today's journey\n",
        "\n",
        "🎮 PLAY ↓ 🧠 UNDERSTAND GAME LOGIC ↓ 🐍 INTRODUCE PYTHON ↓ 🤖 USE GENERATIVE AI ↓ 💻 BUILD A GAME ↓ 🎮 TEST & MODIFY ↓ 🚀 DESIGN YOUR OWN GAME By the end of this session, you will be able to design the logic of a mathematics game and use Generative AI and Python to create a working prototype."
      ],
      "metadata": {
        "id": "fhGhDHRJczJo"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "🎮 EXPERIENCE THE GAME Computational Mathematics Challenge\n",
        "Your mission:\n",
        "\n",
        "Answer the mathematics questions and achieve the highest score possible.\n",
        "\n",
        "Rules 📝 5 questions ❤️ 3 lives ✅ Correct answer = +10 points ❌ Wrong answer = −1 life 💬 Immediate feedback 🏆 Complete all questions or lose all lives\n",
        "\n",
        "Then:\n",
        "\n",
        "Don't look at the code yet. Just play the game."
      ],
      "metadata": {
        "id": "uT07U2Ivc10G"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import random\n",
        "\n",
        "# =========================================================\n",
        "# 🎮 COMPUTATIONAL MATHEMATICS CHALLENGE WITH LEVELS\n",
        "# =========================================================\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# 1. GAME SETTINGS\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "score = 0\n",
        "lives = 3\n",
        "\n",
        "# Define game levels with their respective settings\n",
        "levels = {\n",
        "    \"Basic\": {\n",
        "        \"num_range\": (1, 10),\n",
        "        \"operations\": [\"+\", \"-\"],\n",
        "        \"num_questions\": 5,\n",
        "    },\n",
        "    \"Intermediate\": {\n",
        "        \"num_range\": (5, 15),\n",
        "        \"operations\": [\"+\", \"-\", \"*\"],\n",
        "        \"num_questions\": 5,\n",
        "    },\n",
        "    \"Advanced\": {\n",
        "        \"num_range\": (10, 20),\n",
        "        \"operations\": [\"+\", \"-\", \"*\", \"/\"],\n",
        "        \"num_questions\": 5,\n",
        "    },\n",
        "}\n",
        "\n",
        "print(\"🎮 COMPUTATIONAL MATHEMATICS CHALLENGE\")\n",
        "print(\"=====================================\")\n",
        "print(f\"You have {lives} lives.\")\n",
        "print(\"Correct answer = +10 points\")\n",
        "print(\"Wrong answer = -1 life\")\n",
        "print(\"=====================================\")\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# 2. GAME LOOP (ITERATING THROUGH LEVELS)\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "for level_name, level_settings in levels.items():\n",
        "    if lives == 0:  # If lives run out in a previous level, stop game\n",
        "        break\n",
        "\n",
        "    print(f\"\\n--- Starting {level_name} Level ---\")\n",
        "    print(\"-------------------------------------\")\n",
        "\n",
        "    for question_num in range(1, level_settings[\"num_questions\"] + 1):\n",
        "        if lives == 0:  # If lives run out during current level, stop level\n",
        "            break\n",
        "\n",
        "        # Generate random numbers based on level settings\n",
        "        min_num, max_num = level_settings[\"num_range\"]\n",
        "        num1 = random.randint(min_num, max_num)\n",
        "        num2 = random.randint(min_num, max_num)\n",
        "\n",
        "        # Select a random operation for the current level\n",
        "        operation = random.choice(level_settings[\"operations\"])\n",
        "\n",
        "        # -----------------------------------------------------\n",
        "        # 3. CALCULATE ANSWER (INCLUDING DIVISION LOGIC)\n",
        "        # -----------------------------------------------------\n",
        "\n",
        "        correct_answer = 0\n",
        "        if operation == \"+\":\n",
        "            correct_answer = num1 + num2\n",
        "\n",
        "        elif operation == \"-\":\n",
        "            correct_answer = num1 - num2\n",
        "\n",
        "        elif operation == \"*\":\n",
        "            correct_answer = num1 * num2\n",
        "\n",
        "        elif operation == \"/\":\n",
        "            # Ensure integer division and avoid division by zero\n",
        "            # Make num1 a multiple of num2, and num2 not zero\n",
        "            # Adjust num2 to avoid division by zero\n",
        "            if num2 == 0:\n",
        "                num2 = random.randint(1, max_num) # Re-roll num2 if it's zero\n",
        "\n",
        "            # Adjust num1 to be a multiple of num2, ensuring it's within range\n",
        "            # and that the quotient is a reasonable integer (e.g., between 1 and 10)\n",
        "            temp_quotient = random.randint(1, 10)\n",
        "            num1 = num2 * temp_quotient\n",
        "\n",
        "            # If num1 exceeds max_num, try to adjust it or re-roll numbers if necessary\n",
        "            attempts = 0\n",
        "            while (num1 > max_num or num1 < min_num) and attempts < 5:\n",
        "                num2 = random.randint(1, max_num)\n",
        "                if num2 == 0: # Ensure num2 is never zero\n",
        "                    num2 = 1\n",
        "                temp_quotient = random.randint(1, 10)\n",
        "                num1 = num2 * temp_quotient\n",
        "                attempts += 1\n",
        "\n",
        "            if attempts == 5: # Fallback if suitable numbers aren't found quickly\n",
        "                num1 = random.randint(1, 20) * num2 # Ensure num1 is a multiple\n",
        "                if num1 > max_num:\n",
        "                    num1 = max_num - (max_num % num2 if num2 != 0 else 0) # Make it the largest multiple within range\n",
        "                if num1 < min_num:\n",
        "                    num1 = min_num + (num2 - (min_num % num2 if num2 != 0 else 0)) % num2\n",
        "                if num1 == 0 and min_num > 0:\n",
        "                    num1 = num2\n",
        "\n",
        "            correct_answer = num1 // num2 # Use integer division\n",
        "\n",
        "\n",
        "        # -----------------------------------------------------\n",
        "        # 4. ASK THE PLAYER\n",
        "        # -----------------------------------------------------\n",
        "\n",
        "        print(f\"\\n{level_name} Question {question_num}:\")\n",
        "\n",
        "        try:\n",
        "            answer = int(input(f\"What is {num1} {operation} {num2}? \"))\n",
        "        except ValueError:\n",
        "            print(\"Invalid input. Please enter a number.\")\n",
        "            lives -= 1\n",
        "            print(\"You lost 1 life for invalid input.\")\n",
        "            continue # Skip to next question\n",
        "\n",
        "        # -----------------------------------------------------\n",
        "        # 5. CHECK THE ANSWER\n",
        "        # -----------------------------------------------------\n",
        "\n",
        "        if answer == correct_answer:\n",
        "            print(\"✅ Correct! +10 points!\")\n",
        "            score += 10\n",
        "\n",
        "        else:\n",
        "            print(\"❌ Incorrect!\")\n",
        "            print(\"The correct answer is:\", correct_answer)\n",
        "            lives -= 1\n",
        "            print(\"You lost 1 life.\")\n",
        "\n",
        "        # -----------------------------------------------------\n",
        "        # 6. DISPLAY GAME STATE\n",
        "        # -----------------------------------------------------\n",
        "\n",
        "        print(\"🏆 Score:\", score)\n",
        "        print(\"❤️ Lives:\", lives)\n",
        "\n",
        "        # -----------------------------------------------------\n",
        "        # 7. CHECK GAME OVER (DURING LEVEL)\n",
        "        # -----------------------------------------------------\n",
        "\n",
        "        if lives == 0:\n",
        "            print(\"\\n💥 GAME OVER!\")\n",
        "            break\n",
        "\n",
        "# ---------------------------------------------------------\n",
        "# 8. FINAL RESULT\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "print(\"\\n=====================================\")\n",
        "print(\"🎮 GAME FINISHED\")\n",
        "print(\"=====================================\")\n",
        "print(\"Final Score:\", score)\n",
        "print(\"Lives Remaining:\", lives)\n",
        "\n",
        "# Calculate total possible score\n",
        "total_possible_score = sum(level_settings['num_questions'] * 10 for level_settings in levels.values())\n",
        "\n",
        "if score == total_possible_score:\n",
        "    print(\"🏆 AMAZING! You got everything correct!\")\n",
        "elif score >= total_possible_score * 0.7:\n",
        "    print(\"🌟 GREAT JOB! Keep practising!\")\n",
        "elif score >= total_possible_score * 0.3:\n",
        "    print(\"👍 GOOD TRY! Keep practising your maths!\")\n",
        "else:\n",
        "    print(\"💪 Don't give up! Try again!\")\n",
        "\n",
        "print(\"=====================================\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "T-3zlrQhFEMC",
        "outputId": "8368331e-db6c-42c2-839b-bac19d975ef0"
      },
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "🎮 COMPUTATIONAL MATHEMATICS CHALLENGE\n",
            "=====================================\n",
            "You have 3 lives.\n",
            "Correct answer = +10 points\n",
            "Wrong answer = -1 life\n",
            "=====================================\n",
            "\n",
            "--- Starting Basic Level ---\n",
            "-------------------------------------\n",
            "\n",
            "Basic Question 1:\n",
            "What is 7 - 3? 4\n",
            "✅ Correct! +10 points!\n",
            "🏆 Score: 10\n",
            "❤️ Lives: 3\n",
            "\n",
            "Basic Question 2:\n",
            "What is 2 + 4? 6\n",
            "✅ Correct! +10 points!\n",
            "🏆 Score: 20\n",
            "❤️ Lives: 3\n",
            "\n",
            "Basic Question 3:\n",
            "What is 10 - 1? 9\n",
            "✅ Correct! +10 points!\n",
            "🏆 Score: 30\n",
            "❤️ Lives: 3\n",
            "\n",
            "Basic Question 4:\n",
            "What is 1 + 3? 4\n",
            "✅ Correct! +10 points!\n",
            "🏆 Score: 40\n",
            "❤️ Lives: 3\n",
            "\n",
            "Basic Question 5:\n",
            "What is 5 + 8? 13\n",
            "✅ Correct! +10 points!\n",
            "🏆 Score: 50\n",
            "❤️ Lives: 3\n",
            "\n",
            "--- Starting Intermediate Level ---\n",
            "-------------------------------------\n",
            "\n",
            "Intermediate Question 1:\n",
            "What is 15 * 5? 75\n",
            "✅ Correct! +10 points!\n",
            "🏆 Score: 60\n",
            "❤️ Lives: 3\n",
            "\n",
            "Intermediate Question 2:\n",
            "What is 12 + 5? 17\n",
            "✅ Correct! +10 points!\n",
            "🏆 Score: 70\n",
            "❤️ Lives: 3\n",
            "\n",
            "Intermediate Question 3:\n",
            "What is 5 - 12? -7\n",
            "✅ Correct! +10 points!\n",
            "🏆 Score: 80\n",
            "❤️ Lives: 3\n",
            "\n",
            "Intermediate Question 4:\n",
            "What is 11 * 10? 110\n",
            "✅ Correct! +10 points!\n",
            "🏆 Score: 90\n",
            "❤️ Lives: 3\n",
            "\n",
            "Intermediate Question 5:\n",
            "What is 7 * 14? 98\n",
            "✅ Correct! +10 points!\n",
            "🏆 Score: 100\n",
            "❤️ Lives: 3\n",
            "\n",
            "--- Starting Advanced Level ---\n",
            "-------------------------------------\n",
            "\n",
            "Advanced Question 1:\n",
            "What is 16 - 13? 3\n",
            "✅ Correct! +10 points!\n",
            "🏆 Score: 110\n",
            "❤️ Lives: 3\n",
            "\n",
            "Advanced Question 2:\n",
            "What is 18 - 15? 3\n",
            "✅ Correct! +10 points!\n",
            "🏆 Score: 120\n",
            "❤️ Lives: 3\n",
            "\n",
            "Advanced Question 3:\n",
            "What is 12 + 13? 25\n",
            "✅ Correct! +10 points!\n",
            "🏆 Score: 130\n",
            "❤️ Lives: 3\n",
            "\n",
            "Advanced Question 4:\n",
            "What is 20 / 10? 10\n",
            "❌ Incorrect!\n",
            "The correct answer is: 2\n",
            "You lost 1 life.\n",
            "🏆 Score: 130\n",
            "❤️ Lives: 2\n",
            "\n",
            "Advanced Question 5:\n",
            "What is 13 + 18? 31\n",
            "✅ Correct! +10 points!\n",
            "🏆 Score: 140\n",
            "❤️ Lives: 2\n",
            "\n",
            "=====================================\n",
            "🎮 GAME FINISHED\n",
            "=====================================\n",
            "Final Score: 140\n",
            "Lives Remaining: 2\n",
            "🌟 GREAT JOB! Keep practising!\n",
            "=====================================\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "🎮 Step 1: Run the Starter Game\n",
        "\n",
        "Click ▶️ on the code below and play the game.\n",
        "\n",
        "Don't change anything yet. Just experience the game."
      ],
      "metadata": {
        "id": "oXo8snx4c75f"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "\n",
        "\n",
        "> Add blockquote\n",
        "\n"
      ],
      "metadata": {
        "id": "oTJrhOR9cmt4"
      }
    }
  ]
}